"""
Train a lightweight ToyFCN model on a synthetic multivariate time series dataset.

This script is intended for example usage within CONFETTI package. It creates
a minimal dataset, trains the model, evaluates basic accuracy, and saves the model
to `examples/models/toy_fcn.keras`.
"""

"""
Train a lightweight ToyFCN model on a synthetic multivariate time series dataset.

This script is intended for example usage within the CONFETTI package. It creates
a minimal dataset, trains the model, evaluates basic accuracy, and saves the model
to `examples/models/toy_fcn.keras`.
"""
"""
Train the ToyFCN model on the synthetic dataset generated by generate_toy_dataset.py.
The trained model is saved to: examples/models/toy_fcn.keras
"""
from pathlib import Path
import numpy as np
from confetti.utils import load_multivariate_ts_from_csv
from examples.models.toy_fcn import ToyFCN


def main() -> None:
    base = Path(__file__).resolve().parent.parent / "data"

    # Load training split
    X_train, y_train = load_multivariate_ts_from_csv(base / "toy_train.csv")

    # Load test split
    X_test, y_test = load_multivariate_ts_from_csv(base / "toy_test.csv")

    print("Dataset shapes:")
    print("  X_train:", X_train.shape)
    print("  y_train:", y_train.shape)
    print("  X_test:", X_test.shape)
    print("  y_test:", y_test.shape)

    # Initialize model
    input_shape = X_train.shape[1:]
    num_classes = len(np.unique(y_train))
    model = ToyFCN(input_shape=input_shape, num_classes=num_classes)

    print("\nTraining ToyFCN model...")
    model.fit(X_train, y_train, epochs=30, batch_size=16, verbose=1)

    # Evaluate on test set
    y_pred = model.predict(X_test)
    accuracy = (y_pred == y_test).mean()
    print(f"\nTest accuracy: {accuracy:.3f}")

    print(f"Model saved to: {model.model_path}")


if __name__ == "__main__":
    main()

